### ISSUE TITLE
Portability of Verifiable C

### ISSUE THREAD

**Issue by Lysxia** [PrincetonUniversity/VST#118]
#117 is one instance, among others probably, of CompCert C giving more specific semantics than the C standards that are incompatible with other implementations in the wild.

It would be nice if these refinements could be made explicit and optional, so that disabling them results in a portable dialect that could be used to verify programs meant to be compiled with standard-compliant compilers other than CompCert.

Is that already possible, somehow? If not, how feasible is that idea?

**Comment by andrew-appel** [comment]
Issue #117 is now fixed.

CompCert C is a refinement of the C11 standard, in that some cases are defined in CompCert C where they are undefined in C11.  This is bad, when it causes programs to have correct semantics in CompCert C but crazy semantics in gcc.  It is good, when it causes programs to have the same expected semantics in all of CompCert C, LLVM, and gcc, but the C11 standard would prohibit.

Examples of "bad":  signed integer overflow.  CompCert treats this as defined modulo-2^n twos-complement, but gcc treats it as undefined behavior.

Examples of "good":  using union-variants, storing long integers, loading bytes.  Using union-variants, storing IEEE floats, loading unsigned ints.  (In all of these cases, one must know the instantiation to a particular machine's alignment, integer-size, and big/little-endian rules.)

Each build of Verifiable C is specific to a particular machine's alignment, integer-size, and big/endianness.

I claim (without proof):
Programs that are provable in Verifiable C _exclude_ any "bad" semantics, but permit several (not all) instances of "good" semantics.

This claim is not provable without a formal specification of the exact C semantics desired.  It's not CompCert, for reasons explained above.   It's not Krebbers', which is too strict (for reasons explained above).  Therefore, instead of a Theorem, it's a Desideratum.

In the meantime, if you compile with CompCert you do get a formal guarantee, of course.

**Comment by Lysxia** [comment]
Thanks for the helpful answer. That fix was fast!
