### ISSUE TITLE
Generating tycheck goals depends on the order or the operand

### ISSUE THREAD

**Issue by ildyria** [PrincetonUniversity/VST#142]
I'm quite happy with the latest change in VST (closing https://github.com/PrincetonUniversity/VST/issues/133) and Compcert.

By using the same c file as in https://github.com/PrincetonUniversity/VST/issues/133 I noticed the following small bug. (?)

Doing `forward` on the following C line will directly pass without the need of *entailment*.
`b = b * 2`

Doing `forward` on the following C line will generate an *entailment* goal.
`b = 2 * b`

```coq
Espec : OracleKind
n : Z
Delta_specs : PTree.t funspec
H : 0 <= n < Int.max_signed
Delta := abbreviate : tycontext
______________________________________(1/2)
ENTAIL Delta,
PROP ( )  LOCAL (temp _b (Vlong (Int64.mul (Int64.repr n) (Int64.repr 2))); temp _n (Vlong (Int64.repr n)))  SEP ()
|-- tc_expr Delta ((2) * _n)%expr
```

**Remark:** idem mutatis mutandis for `+` and `-`.

**Comment by andrew-appel** [comment]
Commit 9ae073b fixes this problem, but in the opposite way that you might imagine.
Since late 2017, VST has been stricter about signed-integer overflow than CompCert,
so that VST is closer to the C11 standard.   However, until today VST was not fully
strict about signed-int64 overflow.  Now that this is fixed, you'll discover that
you need the extra entailment in _both_ cases.  See progs/verif_cast_test.v.

**Comment by ildyria** [comment]
Damm. 😢

**Comment by andrew-appel** [comment]
Commit cf34639 improves the situation: now all the extra entailments in this example are solved automatically by the forward tactic, so the user doesn't have to do them at all.  This is because there is enough information above the line (about ranges of values of certain Coq variables) to prove that the signed long-long arithmetic does not overflow.
