### ISSUE TITLE
diagnostic for parameter types in funspec

### ISSUE THREAD

**Issue by dnaumann** [PrincetonUniversity/VST#152]
When the parameter types in a funspec don't match those of the code, the error message could be more clear.
Currently it does not seem to be an error at all, when verifying the body; the error is mismatch at call site.

**Comment by andrew-appel** [comment]
Technically this is not always an error: start_function checks for compatibility (i.e., a cast that does not change representations), rather than identicality.  Start_function did give an error message if they were not compatible.  But in my next commit, I have added a warning if it is compatible but not identical.
