### ISSUE TITLE
forward_call failure on non-standard calling convention

### ISSUE THREAD

**Issue by p3rsik** [PrincetonUniversity/VST#407]
Hello!

I'm using VST 2.5 and Coq 8.11.0.
Got an error saying:
```
Unable to unify  "Tfunction (Tcons (tptr (Tstruct _t noattr)) Tnil)
    tvoid cc_default" with  "Tfunction (Tcons (tptr (Tstruct _t noattr)) Tnil)
    tvoid
    {|
    cc_vararg := false;
    cc_unproto := false;
    cc_structret := true |}".
```
while trying to do `forward_call` on function with non-standard calling convention(return struct set to true). 
I'm attaching minimal example for you to play with.
[rep2.zip](https://github.com/PrincetonUniversity/VST/files/4512255/rep2.zip)

The issue is, is this a bug or intended behavior?
If this isn't a bug, than what workarounds exists to prove such cases?

**Comment by p3rsik** [comment]
[rep2.zip](https://github.com/PrincetonUniversity/VST/files/4512253/rep2.zip)

**Comment by akinanop** [comment]
There is an answer from @andrew-appel that this happens because VST doesn't support struct-copying: https://stackoverflow.com/a/61352047/12296646. 
We ran into this problem after using a workaround around the struct-copying restriction: we define a struct_normalize : statement -> statement function in Coq that replaces struct assignments with field-by-field assignments. So we are working under assumption that there is no struct copy-ing in the function we are calling. That is, we can verify the test_aux from the example above. So the questions are: 1) does forward_call fail only because structret := true in the cc of test_aux definition? 2) given that we normalize the functions and remove stucture-copying from the bodies of the functions, is it safe to change structret value accordingly and proceed with the proof?

**Comment by andrew-appel** [comment]
VST now gives a clearer error message that this feature is not supported, and the user manual (VC.pdf) lists struct-passing as an unsupported feature.
