### ISSUE TITLE
Universe inconsistency with ITree

### ISSUE THREAD

**Issue by liyishuai** [PrincetonUniversity/VST#430]
In coq/coq#12561, I tried to write definitions that utilize VST and ITree, and they can't compile together due to unsatisfiable universe constraints. Should we make `has_ext` universe polymorphic?

**Comment by mansky1** [comment]
There has been at least one version of ITree that worked with the current version of VST. If the current version doesn't work because has_ext is now universe polymorphic, then yes, we should probably update `has_ext` to match. I won't have time to do this soon, but it should be a pretty simple change if you want to make a PR.

**Comment by andrew-appel** [comment]
Has there been any resolution on this issue?  Can we close it?

**Comment by mansky1** [comment]
@liyishuai Are you still having trouble with this?

Separately, I've been making some improvements to the external state infrastructure for DeepWeb, and they haven't yet been merged into master. When I do merge them, if this problem still exists, I will definitely run into it.

**Comment by liyishuai** [comment]
I'm not experiencing this issue recently.
