### ISSUE TITLE
forward_for_simple_bound: Dealing with negative upper bounds

### ISSUE THREAD

**Issue by leowweixiang** [PrincetonUniversity/VST#459]
Hello, I'm a student from the National University of Singapore, and have been using the Verified Software Toolchain. Apologies for asking trivial questions here. I noticed that when using forward_for_simple_bound we're obliged to prove that the upper bound is nonnegative, which brings some nitty-gritty issues in cases such as
`for (int i= -5; i < 0; ++i) { ... }`
and
`for (int i = 0; i < x; ++i) { ... } //where if x is negative, the for loop simply doesn't run and that's ok`

Could I ask for advice on this matter, and how to best deal with it?

EDIT: Also, is there a more appropriate channel for such questions?

**Comment by andrew-appel** [comment]
Use forward_loop instead. 

There's a stackoverflow topic called [verifiable-c](https://stackoverflow.com/search?q=verifiable-c).

**Comment by leowweixiang** [comment]
@andrew-appel Thanks, I'll post future questions there. But I was hoping to avoid `forward_loop`, may I ask what's the significance of this undocumented constraint `0<=hi`?

**Comment by QinshiWang** [comment]
@leowweixiang Thanks for your interest in VST. I think you mean that this constraint is missing in the documentation, thus we should add it. For VST users, `forward_loop` is the most general tactic to deal with loops of any kind. For convenience, we also provide tactics like `forward_for_simple_bound` to simplify proofs in some typical special cases. The design choices here were made in an ad-hoc way. Since loops that start from a negative index are less common than those from a positive index, although it is technically not so hard to support those loops in `forward_for_simple_bound`, we chose not to do so. After all, these do not essentially change the way to use VST.

**Comment by leowweixiang** [comment]
Hi @QinshiWang, I see, thank you very much! I'll proceed with using `forward_loop`
